# Before launching mox, run the quickstart to create config files for running as
# user the mox user (create it on the host system first, e.g. "useradd -d $PWD mox"):
#
# 	docker-compose run mox mox quickstart you@yourdomain.example $(id -u mox)
#
# After following the quickstart instructions you can start mox:
#
# 	docker-compose up

version: '3.7'
services:
  mox:
    # Replace latest with the version you want to run.
    image: docker.io/moxmail/mox:latest
    environment:
      - MOX_DOCKER=... # Quickstart won't try to write systemd service file.
    # Mox needs host networking because it needs access to the IPs of the
    # machine, and the IPs of incoming connections for spam filtering.
    network_mode: 'host'
    volumes:
      - ./config:/mox/config
      - ./data:/mox/data
    working_dir: /mox
    restart: on-failure
    healthcheck:
      test: netstat -nlt | grep ':25 '
      interval: 1s
      timeout: 1s
      retries: 10
